# Generated by Django 2.2.6 on 2020-04-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_Date',
            new_name='pub_date',
        ),
    ]
